version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: backend  # 컨테이너 이름을 backend로 변경
    command: ./wait-for-it.sh mysql-db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env